
export const FETCH_USERS =  `users/FETCH_USERS`;
export const FETCH_USERS_SUCCESS = `users/FETCH_USERS_SUCCESS`;
export const FETCH_USERS_FAILURE = `users/FETCH_USERS_FAILURE`;
export const SELECT_USER = 'SELECT_USER';
export const FETCH_COMMENTS = `comments/FETCH_COMMENTS`;
export const FETCH_COMMENTS_SUCCESS = `comments/FETCH_COMMENTS_SUCCESS`;
export const FETCH_COMMENTS_FAILURE = `comments/FETCH_COMMENTS_FAILURE`;
export const CREATE_COMMENT = `comments/CREATE_COMMENT`;
export const SET_COMMENT_CONTENT = `SET_COMMENT_CONTENT`;
export const FETCH_REPLIES = `replies/FETCH_REPLIES`;
export const FETCH_REPLIES_SUCCESS = `replies/FETCH_REPLIES_SUCCESS`;
export const FETCH_REPLIES_FAILURE = `replies/FETCH_REPLIES_FAILURE`;
export const CREATE_REPLY = `replies/CREATE_REPLY`;