
export const FETCH_USERS =  `users/FETCH_USERS`;
export const FETCH_USERS_SUCCESS = `users/FETCH_USERS_SUCCESS`;
export const FETCH_USERS_FAILURE = `users/FETCH_USERS_FAILURE`;
export const SELECT_USER = 'SELECT_USER';
export const FETCH_COMMENTS = `comments/FETCH_COMMENTS`;
export const FETCH_COMMENTS_SUCCESS = `comments/FETCH_COMMENTS_SUCCESS`;
export const FETCH_COMMENTS_FAILURE = `comments/FETCH_COMMENTS_FAILURE`;
export const CREATE_COMMENT = `comments/CREATE_COMMENT`;
export const SET_COMMENT_CONTENT = `SET_COMMENT_CONTENT`;